### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by MCalerov** [benjiyaya/ComfyUI-KokoroTTS#4]
# ComfyUI Error Report
## Error Details
- **Node ID:** 14
- **Node Type:** SaveAudio
- **Exception Type:** TypeError
- **Exception Message:** 'NoneType' object is not subscriptable
## Stack Trace
```
  File "C:\Users\xxx\Comfytest\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\xxx\xxxx\Comfytest\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\xxxx\xxxx\Comfytest\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:C:\xxxx\xxxx\Comfytest\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:C:\xxxx\xxxx Comfytest\ComfyUI\comfy_extras\nodes_audio.py", line 177, in save_audio
    for (batch_number, waveform) in enumerate(audio["waveform"].cpu()):


it happens the same with the preview node

**Comment by xueqing0622** [comment]
error too
```
got prompt
Initializing KokoroTextToSpeech class.
ERROR: could not load kokoro-onnx in generate: Cannot load file containing pickled data when allow_pickle=False
!!! Exception during processing !!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Admin\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\comfy_extras\nodes_audio.py", line 177, in save_audio
    for (batch_number, waveform) in enumerate(audio["waveform"].cpu()):
                                              ~~~~~^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by tester4488** [comment]
same here
i think is the

ERROR: could not load kokoro-onnx in generate: Cannot load file containing pickled data when allow_pickle=False

but with allow_pickle=True can be a secutity risk

**Comment by benjiyaya** [comment]
here is the similar issue in your system : https://github.com/MIC-DKFZ/nnUNet/issues/509
solution : Please delete all the preprocessed training data and cropped data (nnunet_raw_cropped) of this task and rerun preprocessing. this should fix it.

**Comment by tester4488** [comment]
> here is the similar issue in your system : [MIC-DKFZ/nnUNet#509](https://github.com/MIC-DKFZ/nnUNet/issues/509) solution : Please delete all the preprocessed training data and cropped data (nnunet_raw_cropped) of this task and rerun preprocessing. this should fix it.

Please delete all the preprocessed training data and cropped data 
no idea what you mean....
i'm training nothing (8gb vram)

**Comment by lycos2019** [comment]
> here is the similar issue in your system : [MIC-DKFZ/nnUNet#509](https://github.com/MIC-DKFZ/nnUNet/issues/509) solution : Please delete all the preprocessed training data and cropped data (nnunet_raw_cropped) of this task and rerun preprocessing. this should fix it.

how do i do that

**Comment by MCalerov** [comment]
> here is the similar issue in your system : [MIC-DKFZ/nnUNet#509](https://github.com/MIC-DKFZ/nnUNet/issues/509) solution : Please delete all the preprocessed training data and cropped data (nnunet_raw_cropped) of this task and rerun preprocessing. this should fix it.

It is another different issue..

**Comment by xueqing0622** [comment]
> here is the similar issue in your system : [MIC-DKFZ/nnUNet#509](https://github.com/MIC-DKFZ/nnUNet/issues/509) solution : Please delete all the preprocessed training data and cropped data (nnunet_raw_cropped) of this task and rerun preprocessing. this should fix it.

I don't get the what your mean, go to [MIC-DKFZ/nnUNet#509](https://github.com/MIC-DKFZ/nnUNet/issues/509), still don't know what to do. I have no training anything in this python env.

**Comment by tester4488** [comment]
i think **kokoro-onnx** need to be sanitized.
https://www.taiyenwater2024.com.tw/gasai/cannot-load-file-containing-pickled-data-when-allow-pickle

same problem with the other 2 kokoro  comfyui nodes. all 3 nodes are totaly useless.
windows portable.

**Comment by patientx** [comment]
same here , it doesnt work and neither the other node

**Comment by zhinangubei** [comment]
> 我认为 **kokoro-onnx** 需要净化。 https://www.taiyenwater2024.com.tw/gasai/cannot-load-file-containing-pickled-data-when-allow-pickle
> 
> 其他 2 个 kokoro ComfyUI 节点也存在同样的问题。所有 3 个节点都完全没用。 Windows 便携式。



> i think **kokoro-onnx** need to be sanitized. https://www.taiyenwater2024.com.tw/gasai/cannot-load-file-containing-pickled-data-when-allow-pickle
> 
> same problem with the other 2 kokoro comfyui nodes. all 3 nodes are totaly useless. windows portable.

yes, i install 3 nodes on ubuntu,but same problem

**Comment by Zopiac** [comment]
For me the fix was the same as in https://github.com/stavsap/comfyui-kokoro/issues/1

Seems you need to control the version of kokoro-onnx to 0.3.3 or it will give the error regarding pickles, error out, and try to pass nothing (NoneType) to the PreviewAudio node.

`pip install kokoro-onnx==0.3.3`

**Comment by alenknight** [comment]
> For me the fix was the same as in [stavsap/comfyui-kokoro#1](https://github.com/stavsap/comfyui-kokoro/issues/1)
> 
> Seems you need to control the version of kokoro-onnx to 0.3.3 or it will give the error regarding pickles, error out, and try to pass nothing (NoneType) to the PreviewAudio node.
> 
> `pip install kokoro-onnx==0.3.3`

this worked for me

**Comment by IckeBins67** [comment]
I give up. Nothing worked. Same Error.

**Comment by IckeBins67** [comment]
> For me the fix was the same as in [stavsap/comfyui-kokoro#1](https://github.com/stavsap/comfyui-kokoro/issues/1)
> 
> Seems you need to control the version of kokoro-onnx to 0.3.3 or it will give the error regarding pickles, error out, and try to pass nothing (NoneType) to the PreviewAudio node.
> 
> `pip install kokoro-onnx==0.3.3`

Working now. THX
